language: node_js
deploy:
  provider: s3
  access_key_id: AKIAIJE6YA2ITKGM7RDA
  secret_access_key:
    secure: LU28UQ2CiRCfIebXK4UdGi+ug5kdi0e7kLx2JNfTXEiij5tGyK2XgRZGmj4TkiV6y2eAXy+2pVkIN42ihB4rCk1vJzcjBW68PThAQVcEXVla9pUyWeOBnJ04W3l+tJg2I2W20UXLojTgCOf/XV2kK6DsyMtMde8oOWqkooYArcmG7XLZdcMUx4mRrwwTkUrEmK7uvOYUCvdKy3aDntGM68LRyOSzefiaH0nOCctWst6ui7NBKeO4GB4LKxLj/8dpjwksJa8ElfWB8XMcBH+urwbA5zPbxQt7CjNYKxojqptMGeF28tZzvtTDbdIDj+rxG5GoAsrF0CtDUeKmNeahmD0sQw1HKUMz2MnZ5OjueMiIMTuC5I3kzhCtNl8lKbXLxMlLwSFYedOiRow4e8GRx60pb2t2EVvF4U2D71oGP6dDARNXZA0R8cRDsaa4jdvc0GKKs7b7prNJWztbS7oDFroRb74hbqZ4RLxEPSZaEWKlGSHgUd46bWh5JLYiIjmNctIZU8p9UVSsHaBjbELj9VzuIz3nCRBqHkrMgGwr5scQsiTsgYJiwyhQC7Xs3nuz3ewMcSJuo8EFjminwUP0Bgh6EPFILeDpgl6f9GNwBkow+xXjYDHNFdzC/rRMCwYsPpRTSw2PpNrbkWSFLj8gfT7PZkL84Soxfcv6HS8QLrQ=
  bucket: socialcompany.com
  skip-cleanup: true
  region: us-east-2
  on:
    repo: SocialCompanyInc/PublicWeb
