language: node_js
deploy:
  provider: s3
  access_key_id: AKIAIJE6YA2ITKGM7RDA
  secret_access_key:
    secure: HIci59I4slxfZHUEe8N7i7nbI0ia/s2SwF9BacdVE/IEajxp9IG1qYsZQU7DBJGODnHa2tnOfUk/FOtidwhfhKsDpvccuFkZMNZgU8jSnqP4sG6nJ1DyOqYX6eMw42RHe3gdIIOpK+wi/j7riqeeJ/3WQr2C7kilCEV2lDEp5jg8FvCuMUR8QHtscXAzY9g5Zl0Z8YnOPcCDwutV9Je6qM/fhvNYy4k8XIPGI5aNadLYs3XUi5PR86fU4LZdM8JGvOE7I2ZKLSOzdyiE4G9+WbNExlc1eAIls1TuaSTqpiMsKMzk2+9T8cogcmBZKeYRrhntNqoUlrlL2qw4eaiSMhJjL99Zcr29305MJNoxZTwbPuKvW/NbBX0QR9F+k4lzljM/bh0Jt/oxc9A87vMKp5CynJIYXu0BhaJPONUEs7fJBwJh8mrQklBUQG2hMtdns3JWkzuc7iEifyQ2ZsKwaskanebi7AenEY/hnx1l81HCYAyYHsRLoOeWjltS70mP+GkRS2ptzf9ZHdOQfcKG52Ge5n3fwq+GErKgpzHprFbRTa6jCE1StAGu+Mga68HqKdTaGVWgWAhBhh7Yq+SdKrTqrofCegR56l3RabOxc4ovGBpAGxI71LKawy8XvsVrHnYDXLE1pQYWlSLylJgGZCLHVy7kffdMsG2xIl6TomU=
  bucket: "socialcompany.com.s3-website.us-east-2.amazonaws.com"
