language: node_js
deploy:
  provider: s3
  access_key_id: AKIAIJE6YA2ITKGM7RDA
  secret_access_key:
    secure: SWJzdC3ZuMIw/Bl2ASLhhwKcPyEV9uYTH9TSdOqNbbtuALcdbmLMYNL6enwBFy8KkegYZevKWE+3hPcp/gUwKsxpmAclZH3JLpeHd+X0Ujm+jSdeYGpS5YVYY1mtzcXVSJ89jgWZ4/XLDRYOAhA9KFEzRpYgBAPCDERPqmmTDE/ndXNi/+zumMlFbA5EUadCkTsmaH7JuK9E2aiIqAdGm75j7VzgEv/UewmPnHWzt2ptdbALPethfsQ/sY6S88qv+F6gzPjsHB782Lq7C5U355Jr/kf/5G5KZq+/n0WX2Esa+piNYtZ497EXzW4XB7InvIA+EE41UgZZGPievVJlPKqnY/Mpic0cP7PRjdI5Shq8Gkk8UPYqVdxp+JRHDabmQ8EXPRjsITwN4khEeOlh++mjJePgo2o34+oKSIi1ehf/BsPgsA3IsgdM4mnctuBrwNxQ7vBPKdSd/HtKss3MpBltqo/dOEMT5+7sY0J4HBFLB6yW6YQ++Iok19/QZSRMhPjrxGq0Hgvt44nfiKtCVHQIRgTzgRMNpZuLE90BS2/mNuov/04FW6MIgKr6DJRED97u6o08J56gTczt6iXsTcqelQVgomRdL+7X2vzZeHcMRUFRcxEnVtCB8R40bD0x+CygDbfmwyc7XLSZ01atvwzHdyJ+9qn4bVF7CzJIn5U=
  region: us-east-2
  bucket: socialcompany.com
